/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as ApiCookietestRouteImport } from './routes/api/cookietest'
import { Route as ProtectedCustomIndexRouteImport } from './routes/_protected/custom/index'
import { Route as ProtectedFinishedIndexRouteImport } from './routes/_protected/finished/index'
import { Route as ProtectedReadingIndexRouteImport } from './routes/_protected/reading/index'
import { Route as ProtectedSearchIndexRouteImport } from './routes/_protected/search/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiBlobDeleteRouteImport } from './routes/api/blob/delete'
import { Route as ApiBlobUploadRouteImport } from './routes/api/blob/upload'
import { Route as LegalPrivacyPolicyIndexRouteImport } from './routes/legal/privacy-policy/index'
import { Route as LegalTermsAndConditionsIndexRouteImport } from './routes/legal/terms-and-conditions/index'
import { Route as ProtectedBookBookIdIndexRouteImport } from './routes/_protected/book/$bookId/index'
import { Route as ProtectedCustomBookIdIndexRouteImport } from './routes/_protected/custom/$bookId/index'
import { Route as ProtectedCustomNewIndexRouteImport } from './routes/_protected/custom/new/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCookietestRoute = ApiCookietestRouteImport.update({
  id: '/api/cookietest',
  path: '/api/cookietest',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedCustomIndexRoute = ProtectedCustomIndexRouteImport.update({
  id: '/custom/',
  path: '/custom/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedFinishedIndexRoute = ProtectedFinishedIndexRouteImport.update({
  id: '/finished/',
  path: '/finished/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedReadingIndexRoute = ProtectedReadingIndexRouteImport.update({
  id: '/reading/',
  path: '/reading/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedSearchIndexRoute = ProtectedSearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlobDeleteRoute = ApiBlobDeleteRouteImport.update({
  id: '/api/blob/delete',
  path: '/api/blob/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlobUploadRoute = ApiBlobUploadRouteImport.update({
  id: '/api/blob/upload',
  path: '/api/blob/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyPolicyIndexRoute = LegalPrivacyPolicyIndexRouteImport.update({
  id: '/legal/privacy-policy/',
  path: '/legal/privacy-policy/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsAndConditionsIndexRoute =
  LegalTermsAndConditionsIndexRouteImport.update({
    id: '/legal/terms-and-conditions/',
    path: '/legal/terms-and-conditions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProtectedBookBookIdIndexRoute =
  ProtectedBookBookIdIndexRouteImport.update({
    id: '/book/$bookId/',
    path: '/book/$bookId/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedCustomBookIdIndexRoute =
  ProtectedCustomBookIdIndexRouteImport.update({
    id: '/custom/$bookId/',
    path: '/custom/$bookId/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedCustomNewIndexRoute = ProtectedCustomNewIndexRouteImport.update({
  id: '/custom/new/',
  path: '/custom/new/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/cookietest': typeof ApiCookietestRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blob/delete': typeof ApiBlobDeleteRoute
  '/api/blob/upload': typeof ApiBlobUploadRoute
  '/custom/': typeof ProtectedCustomIndexRoute
  '/finished/': typeof ProtectedFinishedIndexRoute
  '/reading/': typeof ProtectedReadingIndexRoute
  '/search/': typeof ProtectedSearchIndexRoute
  '/legal/privacy-policy/': typeof LegalPrivacyPolicyIndexRoute
  '/legal/terms-and-conditions/': typeof LegalTermsAndConditionsIndexRoute
  '/book/$bookId/': typeof ProtectedBookBookIdIndexRoute
  '/custom/$bookId/': typeof ProtectedCustomBookIdIndexRoute
  '/custom/new/': typeof ProtectedCustomNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/cookietest': typeof ApiCookietestRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blob/delete': typeof ApiBlobDeleteRoute
  '/api/blob/upload': typeof ApiBlobUploadRoute
  '/custom': typeof ProtectedCustomIndexRoute
  '/finished': typeof ProtectedFinishedIndexRoute
  '/reading': typeof ProtectedReadingIndexRoute
  '/search': typeof ProtectedSearchIndexRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyIndexRoute
  '/legal/terms-and-conditions': typeof LegalTermsAndConditionsIndexRoute
  '/book/$bookId': typeof ProtectedBookBookIdIndexRoute
  '/custom/$bookId': typeof ProtectedCustomBookIdIndexRoute
  '/custom/new': typeof ProtectedCustomNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/api/cookietest': typeof ApiCookietestRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blob/delete': typeof ApiBlobDeleteRoute
  '/api/blob/upload': typeof ApiBlobUploadRoute
  '/_protected/custom/': typeof ProtectedCustomIndexRoute
  '/_protected/finished/': typeof ProtectedFinishedIndexRoute
  '/_protected/reading/': typeof ProtectedReadingIndexRoute
  '/_protected/search/': typeof ProtectedSearchIndexRoute
  '/legal/privacy-policy/': typeof LegalPrivacyPolicyIndexRoute
  '/legal/terms-and-conditions/': typeof LegalTermsAndConditionsIndexRoute
  '/_protected/book/$bookId/': typeof ProtectedBookBookIdIndexRoute
  '/_protected/custom/$bookId/': typeof ProtectedCustomBookIdIndexRoute
  '/_protected/custom/new/': typeof ProtectedCustomNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/cookietest'
    | '/api/auth/$'
    | '/api/blob/delete'
    | '/api/blob/upload'
    | '/custom/'
    | '/finished/'
    | '/reading/'
    | '/search/'
    | '/legal/privacy-policy/'
    | '/legal/terms-and-conditions/'
    | '/book/$bookId/'
    | '/custom/$bookId/'
    | '/custom/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/cookietest'
    | '/api/auth/$'
    | '/api/blob/delete'
    | '/api/blob/upload'
    | '/custom'
    | '/finished'
    | '/reading'
    | '/search'
    | '/legal/privacy-policy'
    | '/legal/terms-and-conditions'
    | '/book/$bookId'
    | '/custom/$bookId'
    | '/custom/new'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/api/cookietest'
    | '/api/auth/$'
    | '/api/blob/delete'
    | '/api/blob/upload'
    | '/_protected/custom/'
    | '/_protected/finished/'
    | '/_protected/reading/'
    | '/_protected/search/'
    | '/legal/privacy-policy/'
    | '/legal/terms-and-conditions/'
    | '/_protected/book/$bookId/'
    | '/_protected/custom/$bookId/'
    | '/_protected/custom/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  ApiCookietestRoute: typeof ApiCookietestRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBlobDeleteRoute: typeof ApiBlobDeleteRoute
  ApiBlobUploadRoute: typeof ApiBlobUploadRoute
  LegalPrivacyPolicyIndexRoute: typeof LegalPrivacyPolicyIndexRoute
  LegalTermsAndConditionsIndexRoute: typeof LegalTermsAndConditionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cookietest': {
      id: '/api/cookietest'
      path: '/api/cookietest'
      fullPath: '/api/cookietest'
      preLoaderRoute: typeof ApiCookietestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/custom/': {
      id: '/_protected/custom/'
      path: '/custom'
      fullPath: '/custom/'
      preLoaderRoute: typeof ProtectedCustomIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/finished/': {
      id: '/_protected/finished/'
      path: '/finished'
      fullPath: '/finished/'
      preLoaderRoute: typeof ProtectedFinishedIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/reading/': {
      id: '/_protected/reading/'
      path: '/reading'
      fullPath: '/reading/'
      preLoaderRoute: typeof ProtectedReadingIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/search/': {
      id: '/_protected/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof ProtectedSearchIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blob/delete': {
      id: '/api/blob/delete'
      path: '/api/blob/delete'
      fullPath: '/api/blob/delete'
      preLoaderRoute: typeof ApiBlobDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blob/upload': {
      id: '/api/blob/upload'
      path: '/api/blob/upload'
      fullPath: '/api/blob/upload'
      preLoaderRoute: typeof ApiBlobUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy-policy/': {
      id: '/legal/privacy-policy/'
      path: '/legal/privacy-policy'
      fullPath: '/legal/privacy-policy/'
      preLoaderRoute: typeof LegalPrivacyPolicyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms-and-conditions/': {
      id: '/legal/terms-and-conditions/'
      path: '/legal/terms-and-conditions'
      fullPath: '/legal/terms-and-conditions/'
      preLoaderRoute: typeof LegalTermsAndConditionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/book/$bookId/': {
      id: '/_protected/book/$bookId/'
      path: '/book/$bookId'
      fullPath: '/book/$bookId/'
      preLoaderRoute: typeof ProtectedBookBookIdIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/custom/$bookId/': {
      id: '/_protected/custom/$bookId/'
      path: '/custom/$bookId'
      fullPath: '/custom/$bookId/'
      preLoaderRoute: typeof ProtectedCustomBookIdIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/custom/new/': {
      id: '/_protected/custom/new/'
      path: '/custom/new'
      fullPath: '/custom/new/'
      preLoaderRoute: typeof ProtectedCustomNewIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedCustomIndexRoute: typeof ProtectedCustomIndexRoute
  ProtectedFinishedIndexRoute: typeof ProtectedFinishedIndexRoute
  ProtectedReadingIndexRoute: typeof ProtectedReadingIndexRoute
  ProtectedSearchIndexRoute: typeof ProtectedSearchIndexRoute
  ProtectedBookBookIdIndexRoute: typeof ProtectedBookBookIdIndexRoute
  ProtectedCustomBookIdIndexRoute: typeof ProtectedCustomBookIdIndexRoute
  ProtectedCustomNewIndexRoute: typeof ProtectedCustomNewIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedCustomIndexRoute: ProtectedCustomIndexRoute,
  ProtectedFinishedIndexRoute: ProtectedFinishedIndexRoute,
  ProtectedReadingIndexRoute: ProtectedReadingIndexRoute,
  ProtectedSearchIndexRoute: ProtectedSearchIndexRoute,
  ProtectedBookBookIdIndexRoute: ProtectedBookBookIdIndexRoute,
  ProtectedCustomBookIdIndexRoute: ProtectedCustomBookIdIndexRoute,
  ProtectedCustomNewIndexRoute: ProtectedCustomNewIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  ApiCookietestRoute: ApiCookietestRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBlobDeleteRoute: ApiBlobDeleteRoute,
  ApiBlobUploadRoute: ApiBlobUploadRoute,
  LegalPrivacyPolicyIndexRoute: LegalPrivacyPolicyIndexRoute,
  LegalTermsAndConditionsIndexRoute: LegalTermsAndConditionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
